settings:
  wait_time: 15
  progress_bar_done_sprite: ✔
  progress_bar_error_sprite: ✘
  progress_bar_empty_sprite: ▱
  progress_bar_full_sprite: ▰
  prefered_text_editor: nano
  prefered_flatpak_repo: flathub
  notifications: True
  cromha_manager_logging: True
package_managers:
  apt: False
  cargo: False
  dnf: False
  flatpak: False
  snapcraft: False
  yum: False
  zypp: False
informations:
  version: 0.1
  distro: none
color_palette:
  color_0: \033[0;30m
  color_1: \033[0;31m
  color_2: \033[0;32m
  color_3: \033[0;33m
  color_4: \033[0;34m
  color_5: \033[0;35m
  color_6: \033[0;36m
  color_7: \033[0;37m
  color_B0: \033[1;30m
  color_B1: \033[1;31m
  color_B2: \033[1;32m
  color_B3: \033[1;33m
  color_B4: \033[1;34m
  color_B5: \033[1;35m
  color_B6: \033[1;36m
  color_B7: \033[1;37m